DROP TABLE IF EXISTS USER;
CREATE TABLE USER(
	USER_ID int NOT NULL AUTO_INCREMENT,
    EMAIL VARCHAR(500) NOT NULL UNIQUE,
    PASS VARCHAR(1000) NOT NULL,
    PAYMENT_STATUS ENUM('PAID','UNPAID','DELINQUENT','OVERPAID','PROCESSING'),
    ACTIVE ENUM('Y','N'),
    PRIMARY KEY (USER_ID)
);

DROP TABLE IF EXISTS PROPERTY;
CREATE TABLE PROPERTY(
	PROPERTY_ID INT NOT NULL AUTO_INCREMENT,
    USER_ID INT NOT NULL,
	P_NAME VARCHAR(500) NOT NULL,
    SQFT INT NOT NULL,
    TYPE ENUM('BAR','RESTAURANT','RESIDENCE','WAREHOUSE','STORE'),
    STORIES INT,
    NOTES VARCHAR(2000),
    ADDRESS VARCHAR(500),
    LAT INT,
    LON INT,
	COM_RES ENUM('COMMERCIAL','RESIDENTIAL'),
    PRIMARY KEY (PROPERTY_ID),
    FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID)
);

DROP TABLE IF EXISTS APPOINTMENTS;
CREATE TABLE APPOINTMENTS(
	APPOINTMENT_ID INT NOT NULL AUTO_INCREMENT,
    PROPERTY_ID INT NOT NULL,
    SCHEDULED_DT DATETIME NOT NULL,
    COMPLETED_DT DATETIME,
    APP_STATUS ENUM('COMPLETE','IN PROGRESS','DELAYED','CANCELED BY CLIENT','CANCELED BY US','SCHEDULED'),
    PRIMARY KEY (APPOINTMENT_ID),
	FOREIGN KEY(PROPERTY_ID) REFERENCES PROPERTY(PROPERTY_ID),
    CONSTRAINT NO_DUPS UNIQUE (PROPERTY_ID, SCHEDULED_DT, APP_STATUS),
    CONSTRAINT CHK_COMPLETE CHECK ((COMPLETED_DT IS NULL AND APP_STATUS <> 'COMPLETE') OR (COMPLETED_DT IS NOT NULL AND APP_STATUS = 'COMPLETE'))
);