DELIMITER //
CREATE PROCEDURE GET_FUTURE_APPOINTMENTS_BY_USER_ID(IN U_ID INT)
BEGIN
	SELECT * FROM APPOINTMENTS WHERE PROPERTY_ID IN (SELECT PROPERTY_ID FROM PROPERTY WHERE USER_ID=U_ID) AND (SCHEDULED_DT > CURRDATE() OR APP_STATUS IN ('SCHEDULED','IN PROGRESS','DELAYED'));
END //

CREATE PROCEDURE GET_PAST_APPOINTMENTS_BY_USER_ID(IN U_ID INT)
BEGIN
	SELECT * FROM APPOINTMENTS WHERE PROPERTY_ID IN (SELECT PROPERTY_ID FROM PROPERTY WHERE USER_ID=U_ID) AND (SCHEDULED_DT < CURRDATE() AND APP_STATUS IN ('COMPLETE','IN PROGRESS','CANCELED BY CLIENT','CANCELED BY US'));
END //

CREATE PROCEDURE GET_ALL_APPOINTMENTS_BY_USER_ID(IN U_ID INT)
BEGIN
	SELECT * FROM APPOINTMENTS WHERE PROPERTY_ID IN (SELECT PROPERTY_ID FROM PROPERTY WHERE USER_ID=U_ID);
END //

CREATE PROCEDURE GET_FUTURE_APPOINTMENTS_BY_PROPERTY_ID(IN P_ID INT)
BEGIN
	SELECT * FROM APPOINTMENTS WHERE PROPERTY_ID = P_ID AND (SCHEDULED_DT > CURRDATE() OR APP_STATUS IN ('SCHEDULED','IN PROGRESS','DELAYED'));
END //

CREATE PROCEDURE GET_PAST_APPOINTMENTS_BY_PROPERTY_ID(IN P_ID INT)
BEGIN
	SELECT * FROM APPOINTMENTS WHERE PROPERTY_ID = P_ID AND (SCHEDULED_DT < CURRDATE() OR APP_STATUS AND APP_STATUS IN ('COMPLETE','IN PROGRESS','CANCELED BY CLIENT','CANCELED BY US'));
END //

CREATE PROCEDURE GET_ALL_APPOINTMENTS_BY_PROPERTY_ID(IN P_ID INT)
BEGIN
	SELECT * FROM APPOINTMENTS WHERE PROPERTY_ID = P_ID;
END //

DROP PROCEDURE IF EXISTS AUTH_USER;
//

CREATE PROCEDURE AUTH_USER ( IN EM VARCHAR(500), IN PASSHASH VARCHAR(1000) )
BEGIN
	SELECT USER_ID, PASS, EMAIL, PAYMENT_STATUS, ACTIVE FROM USER WHERE EMAIL = EM AND PASS = PASSHASH;
END //

//
CREATE PROCEDURE GET_PROPERTIES_BY_USER_ID( IN U_ID INT)
BEGIN
	SELECT * FROM PROPERTY WHERE USER_ID = U_ID;
END //

CREATE PROCEDURE GET_PROPERTIES_BY_EMAIL( IN EM VARCHAR(500))
BEGIN
	SELECT * FROM PROPERTY WHERE USER_ID IN ( SELECT USER_ID FROM USER WHERE EMAIL = EM);
END //

CREATE PROCEDURE GET_PROPERTY_BY_APPT_ID( IN APPT_ID INT)
BEGIN
	SELECT * FROM PROPERTY WHERE PROPERTY_ID IN (SELECT PROPERTY_ID FROM APPOINTMENT WHERE APPOINTMENT_ID=APPT_ID);
END //
