-- DROP PROCS
DROP PROCEDURE GET_FUTURE_APPOINTMENTS_BY_USER_ID;
DROP PROCEDURE GET_PAST_APPOINTMENTS_BY_USER_ID;
DROP PROCEDURE GET_ALL_APPOINTMENTS_BY_USER_ID;
DROP PROCEDURE GET_FUTURE_APPOINTMENTS_BY_PROPERTY_ID;
DROP PROCEDURE GET_PAST_APPOINTMENTS_BY_PROPERTY_ID;
DROP PROCEDURE GET_ALL_APPOINTMENTS_BY_PROPERTY_ID;
DROP PROCEDURE AUTH_USER;
DROP PROCEDURE GET_PROPERTIES_BY_USER_ID;
DROP PROCEDURE GET_PROPERTIES_BY_EMAIL;
DROP PROCEDURE GET_PROPERTY_BY_APPT_ID;
DROP PROCEDURE ADD_USER;
DROP PROCEDURE ADD_PROPERTY;
DROP PROCEDURE ADD_APPOINTMENT;

-- DROP TABLES
DROP TABLE APPOINTMENTS;
DROP TABLE PROPERTY;
DROP TABLE USER;

